pull request
sasaranAndrei/assignment1 pull request #1
Opened 2021-04-12 09:50 UTC by sasaranAndrei

2021-04-12 10:00 UTC, chioreandan requested changes

2021-04-12 10:00 UTC, chioreandan commented on source/index.html
> +
You don't need all those empty spaces

2021-04-12 10:00 UTC, chioreandan commented on source/index.html
> +
remove empty space

2021-04-12 10:00 UTC, chioreandan commented on source/index.html
> +                <!--LOGO-->
no need for comments, it is pretty obvious what this section is

2021-04-12 10:00 UTC, chioreandan commented on source/index.html
> +
remove emtpy line

2021-04-12 13:24 UTC, sasaranAndrei commented
@chioreandan @VictorMotogna @AdrianFlorian

2021-04-13 07:16 UTC, AdrianFlorian requested changes
Getting there, Sasa! Please add a descriptive title to the PR and a good description of the changes. Use this as an inspiration: cristichirtos/RoR-internship-assignment-1#1

Looking forward to seeing some JS :-)

2021-04-13 07:16 UTC, AdrianFlorian commented on source/index.html
> +                    <!-- 80 empty space for the left part-->
do you really need the comment here? :-)

2021-04-13 07:16 UTC, AdrianFlorian commented on source/style.css
> +    /* make text invisible, but let the underline color to be white */
same here, do you really need the comment ? :D

2021-04-14 09:27 UTC, sasaranAndrei commented
@chioreandan @AdrianFlorian

2021-04-15 06:09 UTC, chioreandan requested changes

2021-04-15 06:09 UTC, chioreandan commented on source/style.css
> +
remove empty line

2021-04-15 06:09 UTC, chioreandan commented on source/style.css
> +}
add empty line

2021-04-15 06:09 UTC, chioreandan commented on source/style.css
> +}
What if you need 2 add 2 selects on the same page but with the red background color?

2021-04-15 06:09 UTC, chioreandan commented on source/style.css
> +}
What if in another part of the page you need to have an anchor tag (<a>) but with the color red?

2021-04-15 06:09 UTC, chioreandan commented on source/index.html
> +<!DOCTYPE html>
check tab spacing for this file. I think it is 4 spaces instead of 2

2021-04-15 09:48 UTC, AdrianFlorian approved these changes
@sasaranAndrei nice job!

2021-04-15 09:48 UTC, AdrianFlorian commented on source/animation.js
> +function sliderChange (){
nice, love the naming here ;)

2021-04-19 08:22 UTC, merged